### ISSUE TITLE
Add test coverage tracking

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-s3#103]
This repo should have test coverage tracking so that we can easily:

 - See that new code is fully covered with tests
 - Monitor test coverage over time

**Comment by tony-cj** [comment]
Just added  https://github.com/mapbox/tilelive-s3/commit/cf26642d6d602c912e3fc0f9a06bbd66ec993692

**Comment by springmeyer** [comment]
@tony-cj thanks for starting to work on this! Can you please plan to create a separate PR that only adds coverage, first? This PR should be working and merged before (and separately) from the changes related to the `option-7` branch. Also instead of `"upload-coverage": "codecov -f .nyc_output/*.json"` it should be `"upload-coverage": "nyc report --reporter json && codecov -f ./coverage/coverage-final.json"` which will support "partials" as described at https://docs.codecov.io/v4.3.6/docs/node.

**Comment by tony-cj** [comment]
I created a PR for this.

**Comment by springmeyer** [comment]
Done in #104
