### ISSUE TITLE
Retry like you mean it mode

### ISSUE THREAD

**Issue by rclark** [mapbox/tilelive-s3#38]
The [number of times we retry requests](https://github.com/mapbox/tilelive-s3/commit/36cb4c3e8e9a55146f0f98f297e475c7316abfe6) was adjusted, now its set to 5 times, I believe.

I'm seeing a lot of tile copy operations ending in `Error: socket hang up`, being automatically retried, and succeeding the second time. This leads me to believe that we should either retry more, or provide a retry-forever mode on certain types of network errors.

cc @willwhite

**Comment by yhahn** [comment]
Hrm, where did we land last time we discussed this ideally being in the purview of tilelive copy streams rather than implementing modules themselves?

**Comment by springmeyer** [comment]
is this still needing fixed or can it be closed?
