### ISSUE TITLE
Node v0.12.x support

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-s3#40]
- [x] Use [Nan](https://github.com/nodejs/nan)
 - [x] upgrade bundled libpng (which has known security vulnerabilities)
 - [x] merge #39
 - [x] start testing against node v.12 for travis
 - [ ] new tag/release

**Comment by jakepruitt** [comment]
@springmeyer is there anything I can help with here? I'd be willing to go down the rabbit hole of v.12, and possibly port the C++ code over to node in the process (if needed).

**Comment by mikemorris** [comment]
@jakepruitt I recently added Node v0.12 and iojs support to node-mbgl in https://github.com/mapbox/node-mapbox-gl-native/pull/88, feel free to ping me with any questions if you take this on.

**Comment by springmeyer** [comment]
@jakepruitt @mikemorris - great, I think the path of least resistance here is to take the code as is and upgrade it to compile/run on node v0.12.x while making minimal changes (as per the list of todos above). Happy to be available to help on this @jakepruitt if you'd like to take it on.

**Comment by ianshward** [comment]
@jakepruitt where did you leave off on this?

**Comment by springmeyer** [comment]
This is happening now over at https://github.com/mapbox/tilelive-s3/pull/44#issuecomment-118658043. The next step is to fix the failing tests in master so that branch can be merged and released.

**Comment by springmeyer** [comment]
closing, we build for node v0.12.x, the problem now is that we need to fix the tests and publish: https://github.com/mapbox/tilelive-s3/pull/53
