### ISSUE TITLE
Use aws-sdk for reading tiles

### ISSUE THREAD

**Issue by willwhite** [mapbox/tilelive-s3#46]
Use aws-sdk for reading tiles, which will enable authenticated requests and features like retries for S3.

**Comment by rclark** [comment]
To be clear, seems like the goals would be to:
- exert more control over retries. Configurable by the caller? Or predefined settings?
- allow requests for private tiles
- [?] read from buckets in other regions
- [victory lap] remove dependency on node-tilejson
