### ISSUE TITLE
v3.2.4 release

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-s3#66]
Next release (is likely) `v3.2.4`. This issue to track that when we release `v3.2.4` as this will be the first release with node v0.12.x support and we'll want to:

 - [ ] also consider upgrading out of date deps: https://david-dm.org/mapbox/tilelive-s3
 - [ ] add a note to changelog about node v0.12.x support + binaries
 - [x] ~~Followup after this is done will be to~~ get 4/5x support going: https://github.com/mapbox/tilelive-s3/issues/63

/cc @yhahn @mikemorris

**Comment by willwhite** [comment]
Still relevant @springmeyer ?

**Comment by springmeyer** [comment]
Thanks @willwhite - no, no longer relevant!
