### ISSUE TITLE
release notes for for 6.2.0

### ISSUE THREAD

**Issue by willwhite** [mapbox/tilelive-s3#81]
@dnomadb can you add release notes for v6.2.0 to the changelog?

https://github.com/mapbox/tilelive-s3/blob/master/CHANGELOG.md

**Comment by dnomadb** [comment]
@rclark is this right(ish)?
# 6.2.0
 - Adds support for respecting an `AWS_S3_ENDPOINT` as an environment variable for mocking s3 locally

**Comment by rclark** [comment]
Sure, I tweaked the grammar in your post a little tho.
